### ISSUE TITLE
Pack contribution is error-prone

### ISSUE THREAD

**Issue by romainricard** [romainricard/signalstickers#51]
I see a lot of invalid PR from people pasting the JSON blob in the wrong place (e.g. after the closing bracket), as JSON is not that easy for non-developpers. This was totally predictable, I should have thought about it in the first place.

YAML could make the contribution easier, but it would mean probably converting it to JSON for the front-end to consume it easily.

Proposed format (for a given pack)
```YAML
ae1d343accdec586fe19954a6be7aee9:
  key: ffea9831b6af7617e4ab1b3868ce6f26f5c7c8ab3f05fb8d68b436f9253232ab
  tags: foo, bar
  nsfw: false
```

Other proposed format (for a given pack):
```YAML
ae1d343accdec586fe19954a6be7aee9:
  key: ffea9831b6af7617e4ab1b3868ce6f26f5c7c8ab3f05fb8d68b436f9253232ab
  tags:
    - foo
    - bar
  nsfw: true
```
